on:
  schedule:
    - cron: '5 11 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add dummy commit - 22f3000486@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date -u)" >> daily-commit-log.txt
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add daily-commit-log.txt
          git commit --allow-empty -m "Daily empty commit"
          git push
